### PR TITLE
docs: update documentation, beginner-friendly (#64)

### LINKED ISSUE #64: update documentation for getting started
There needs to some enhancements and minor changes done to the documentation of the repository.
- Creating a step by step by step procedure for making a PR.
- The point of fixing a merge conflict is missing, would like to add that to the documentation, by adding some procedural steps of commands.

I would like to start working on it.

### PR DESCRIPTION
**Pull request by tusharnankani**
Closes #64 

This is how the [updated README](https://github.com/tusharnankani/Get-Started-NWoC20/blob/readme-doc-update/README.md) looks like. 

Let me know if any changes are to be made.

### CODE REVIEW

**Comment by s-ayush2903** [comment]
Very first rule is to not to work on the issue that isn't approved by any of the repo maintainer and that too if you ain't assigned to it

**Comment by s-ayush2903** [comment]
We neither need that issue nor the PR, as we've linked the resource in the readme. And this repo is just to give people an idea how to open a PR and that's, so we don't accept any issues opened on it, rather fix 'em internally without any PRs on our own.

**Comment by tusharnankani** [comment]
> Very first rule is to not to work on the issue that isn't approved by any of the repo maintainer and that too if you ain't assigned to it

I am really sorry. I didn't know that all of this is part of an event. I discovered it later. Apologies from my end.

**Comment by s-ayush2903** [comment]
>  I am really sorry. I didn't know that all of this is part of an event. I discovered it later. Apologies from my end.

Nope, this isn't about this particular program only, this is the general Open Source workflow, please don't work on the issue that isn't approved by some maintainer of the repo as working on it could prove to be a waste of your time if you mis-understood the functionality and worked on it. So leave the issue upto maintainer for approval, when get a green check, then work on it.

**Comment by tusharnankani** [comment]
I also have made a PR on the website repository of this program. Apologies for that too. @s-ayush2903

**Comment by s-ayush2903** [comment]
Ah, no need to apologize. Don't worry much about it, no one is going to judge anyone. end of the day, all this is being done to make curious students learn new stuff, and it values a lot if anyone takes something useful from here to their home

**Pull request closed without merging**
