### PR TITLE
add Balaram_Ghosh.txt file

### PR DESCRIPTION
**Pull request by BALARAMGHOSH**

### CODE REVIEW

**Comment by Ankit7Das** [comment]
@BALARAMGHOSH  you have added two files in the contributors folder with your name.

**Comment by BALARAMGHOSH** [comment]
> @BALARAMGHOSH you have added two files in the contributors folder with your name.

At first I was add the file that was my name with underslash (_). Then I notice that I have to upload the file which is named as my github username. Then I add the file which is named as mentioned. Now I have deleted that file which is uploaded by mistake,

**Review by Ankit7Das — APPROVED** [review]

**Comment by Ankit7Das** [comment]
Its alright, take care next time. I've merged it and assigned you the points👍. Keep up the good work!

**Comment by BALARAMGHOSH** [comment]
> Its alright, take care next time. I've merged it and assigned you the points. Keep up the good work!

Thanks, from next time there will be no mistake.

**Pull request merged**
