### PR TITLE
Participating in NJACKWinterOfCode

### PR DESCRIPTION
**Pull request by HimeshNayak**
Added my name Himesh Nayak

### CODE REVIEW

**Review by s-ayush2903 — COMMENTED** [review]
File should be of extension `txt`

**Review by prathamesh-borse — CHANGES_REQUESTED** [review]
@HimeshNayak You should add the HimeshNayak.txt extension in your contributors.md file check this send again your PR.

**Comment by HimeshNayak** [comment]
> File should be of extension `txt`

Done

**Review by s-ayush2903 — APPROVED** [review]
Thanks @HimeshNayak for the changes and @prathamesh-borse for the review :)

**Review by prathamesh-borse — APPROVED** [review]
Now it looks good.!
@HimeshNayak Thank you for making your contribution to the open-source world.
Happy Hacking.! 😃 👍

**Comment by prathamesh-borse** [comment]
> Thanks @HimeshNayak for the changes and @prathamesh-borse for the review :)

@s-ayush2903 Thanks to you brother its because the beginners can contribute to the open-source using this project thanks for making it.! 💯

**Pull request merged**
